import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Alias sang đúng token của design-system.css (Mắt Bão Mockup Kit) — KHÔNG
        // định nghĩa màu mới ở đây, chỉ trỏ lại để component cũ (port từ dsvh) dùng
        // đúng palette Indigo chính thức thay vì Teal/Orange đã dùng nhầm trước đó.
        canvas: "var(--ds-sidebar-bg)",
        surface: "var(--ds-surface)",
        "surface-2": "var(--ds-bg)",
        "surface-hover": "var(--ds-surface-raised)",
        ink: "var(--ds-fg)",
        "ink-2": "var(--ds-fg-mute)",
        "ink-3": "var(--ds-fg-subtle)",
        stroke: "var(--ds-border)",
        "stroke-soft": "var(--ds-bg)",
        "stroke-hover": "var(--ds-border-strong)",
        "stroke-strong": "var(--ds-border-strong)",
        "stroke-focus": "var(--ds-primary-mute)",
        cream: "var(--ds-primary-light)",
        "cream-100": "var(--ds-primary-light)",
        "cream-200": "var(--ds-primary-light)",
        "cream-300": "var(--ds-primary-mute)",
        "cream-ink": "var(--ds-fg)",
        orange: "var(--ds-primary)",
        "orange-bright": "var(--ds-primary-hover)",
        "orange-strong": "var(--ds-primary-hover)",
        red: "var(--ds-danger)",
        "red-strong": "var(--ds-danger)",
        amber: "var(--ds-warning)",
        "amber-strong": "var(--ds-warning)",
        peach: "var(--ds-warning-bg)",
        yellow: "var(--ds-warning)",
        teal: "var(--ds-success)",
        "teal-strong": "var(--ds-success)",
        mint: "var(--ds-success-bg)",
        magenta: "var(--ds-info)",
        link: "var(--ds-primary)",
        "link-hover": "var(--ds-primary-hover)",

        background: "var(--background)",
        foreground: "var(--foreground)",
        card: { DEFAULT: "var(--card)", foreground: "var(--card-foreground)" },
        popover: { DEFAULT: "var(--popover)", foreground: "var(--popover-foreground)" },
        primary: { DEFAULT: "var(--primary)", foreground: "var(--primary-foreground)" },
        secondary: { DEFAULT: "var(--secondary)", foreground: "var(--secondary-foreground)" },
        muted: { DEFAULT: "var(--muted)", foreground: "var(--muted-foreground)" },
        accent: { DEFAULT: "var(--accent)", foreground: "var(--accent-foreground)" },
        destructive: { DEFAULT: "var(--destructive)", foreground: "var(--destructive-foreground)" },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
      },
      fontSize: {
        micro: "var(--ds-font-size-xs)",
        meta: "var(--ds-font-size-xs)",
        caption: "var(--ds-font-size-sm)",
        body: "var(--ds-font-size-base)",
        title: "var(--ds-font-size-md)",
        page: "var(--ds-font-size-xl)",
        kpi: "var(--ds-font-size-2xl)",
        hero: "var(--ds-font-size-2xl)",
      },
      borderRadius: {
        card: "var(--ds-radius-lg)",
        lg: "var(--radius)",
        md: "var(--ds-radius)",
        sm: "var(--ds-radius-sm)",
      },
    },
  },
  plugins: [],
} satisfies Config;
