import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        canvas: "var(--color-canvas)",
        surface: "var(--color-surface)",
        "surface-2": "var(--color-surface-2)",
        "surface-hover": "var(--color-surface-hover)",
        ink: "var(--color-ink)",
        "ink-2": "var(--color-ink-2)",
        "ink-3": "var(--color-ink-3)",
        stroke: "var(--color-stroke)",
        "stroke-soft": "var(--color-stroke-soft)",
        "stroke-hover": "var(--color-stroke-hover)",
        "stroke-strong": "var(--color-stroke-strong)",
        "stroke-focus": "var(--color-stroke-focus)",
        cream: "var(--color-cream)",
        "cream-100": "var(--color-cream-100)",
        "cream-200": "var(--color-cream-200)",
        "cream-300": "var(--color-cream-300)",
        "cream-ink": "var(--color-cream-ink)",
        orange: "var(--color-orange)",
        "orange-bright": "var(--color-orange-bright)",
        "orange-strong": "var(--color-orange-strong)",
        red: "var(--color-red)",
        "red-strong": "var(--color-red-strong)",
        amber: "var(--color-amber)",
        "amber-strong": "var(--color-amber-strong)",
        peach: "var(--color-peach)",
        yellow: "var(--color-yellow)",
        teal: "var(--color-teal)",
        "teal-strong": "var(--color-teal-strong)",
        mint: "var(--color-mint)",
        magenta: "var(--color-magenta)",
        link: "var(--color-link)",
        "link-hover": "var(--color-link-hover)",

        background: "var(--background)",
        foreground: "var(--foreground)",
        card: { DEFAULT: "var(--card)", foreground: "var(--card-foreground)" },
        popover: { DEFAULT: "var(--popover)", foreground: "var(--popover-foreground)" },
        primary: { DEFAULT: "var(--primary)", foreground: "var(--primary-foreground)" },
        secondary: { DEFAULT: "var(--secondary)", foreground: "var(--secondary-foreground)" },
        muted: { DEFAULT: "var(--muted)", foreground: "var(--muted-foreground)" },
        accent: { DEFAULT: "var(--accent)", foreground: "var(--accent-foreground)" },
        destructive: { DEFAULT: "var(--destructive)", foreground: "var(--destructive-foreground)" },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
      },
      fontSize: {
        micro: "10px",
        meta: "11px",
        caption: "12px",
        body: "14px",
        title: "16px",
        page: "24px",
        kpi: "28px",
        hero: "34px",
      },
      borderRadius: {
        card: "var(--radius-card)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
} satisfies Config;
